#Configurations for Python Connector Template

# ------------------------------- Workplace Search configuration settings -------------------------------
#Access token for Workplace search authentication
enterprise_search.api_key: "12345678"                                                                                                                       
#Source identifier for the custom source created on the workplace search server
enterprise_search.source_id: "12345678"
#Workplace search server address Example: http://es-host:3002 
enterprise_search.host_url: "http://localhost:3002/"
# ------------------------------- Connector specific configuration settings -------------------------------
#Specifies the objects to be fetched and indexed in the WorkPlace search along with fields that needs to be included/excluded. The list of the objects with a pattern to be included/excluded is provided. By default all the objects are fetched
include:
exclude:
#The timestamp after which all the objects that are modified or created are fetched from the source. By default, all the objects present in the source till the end_time are fetched
start_time : 
#The timestamp before which all the updated objects need to be fetched i.e. the connector wonâ€™t fetch any object updated/created after the end_time. By default, all the objects updated/added till the current time are fetched
end_time : 
#The level of the logs the user wants to use in the log files. The possible values include: debug, info, warn, error. By default, the level is info
log_level: INFO
#The number of retries to perform in case of server error. The connector will use exponential back-off for retry mechanism
retry_count: 3
#Number of threads to be used in multithreading for the sharepoint sync.
source_sync_thread_count: 5
#Number of threads to be used in multithreading for the enterprise search sync.
enterprise_search_sync_thread_count: 5
#Denotes whether document permission will be enabled or not
enable_document_permission: Yes
#The path of csv file containing mapping of the source user name to Workplace user name
connector.user_mapping: ""
